[package]
name = "step_counter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
gfa = "0.10.1"
handlegraph = "0.7.0-alpha.9"
flatgfa = { path = "../pollen/flatgfa" }
bstr = "1.9.1"
rayon = "1.8.0"
